{% set version = "0.0.7" %}
# {% set sha256 = "2debe8a5fc000668edbf1b16bdc8de6e8830047bc3f3ffcb2a5636c16137b004" %}

package:
  name: dolang
  version: {{ version }}

source:
  path: ../
  #  fn: master.tar.gz
  #  url: https://github.com/EconForge/dolang.py/archive/master.tar.gz

  # url: https://github.com/EconForge/dolang.py/archive/v{{ version }}.tar.gz
  # sha256: {{ sha256 }}

build:
  script: pip install --no-deps .
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python >= 3.6
    - python
    - numba
    - sympy

test:
  imports:
    - dolang

about:
  home: https://github.com/econforge/Dolang
  license: BSD 2-Clause
  summary: 'Dolo Modeling Language'

extra:
  recipe-maintainers:
    - albop
